// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/fonts/Basel-Book.woff"
    | "/assets/fonts/Basel-Medium.woff"
    | "/assets/fonts/Inter-normal.var.ttf"
    | "/assets/icons/icon128.png"
    | "/assets/icons/icon16.png"
    | "/assets/icons/icon32.png"
    | "/assets/icons/icon48.png"
    | "/assets/icons/lux-logo.svg"
    | "/assets/index.ts"
    | "/assets/onboarding-background-dark.png"
    | "/assets/onboarding-background-light.png"
    | "/background.js"
    | "/content-scripts/ethereum.js"
    | "/content-scripts/injected.js"
    | "/fallback-popup.html"
    | "/onboarding.html"
    | "/sidepanel.html"
    | "/unitagClaim.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
