export enum InterfaceEventName {
  AccountDropdownButtonClicked = 'Account Dropdown Button Clicked',
  ApproveTokenTxnSubmitted = 'Approve Token Transaction Submitted',
  ChainChanged = 'Chain Changed',
  CollectLiquidityFailed = 'Collect Liquidity Failed',
  ConnectWalletButtonClicked = 'Connect Wallet Button Clicked',
  CreatePositionFailed = 'Create Position Failed',
  DecreaseLiquidityFailed = 'Decrease Liquidity Failed',
  EmbeddedWalletCreated = 'Embedded Wallet Created',
  ExploreBannerClicked = 'Explore Banner Clicked',
  ExploreSearchSelected = 'Explore Search Selected',
  ExploreQueryLatency = 'Explore Query Latency',
  ExploreTokenRowClicked = 'Explore Token Row Clicked',
  ExtensionUninstallFeedback = 'Extension Uninstall Feedback',
  ExternalLinkClicked = 'External Link Click',
  FiatOnrampBannerClicked = 'Fiat Onramp Banner Clicked',
  FiatOnrampWidgetOpened = 'Fiat Onramp Widget Opened',
  IncreaseLiquidityFailed = 'Increase Liquidity Failed',
  LanguageSelected = 'Language Selected',
  LimitedWalletSupportToastDismissed = 'Limited Wallet Support Toast Dismissed',
  LimitedWalletSupportToastLearnMoreButtonClicked = 'Limited Wallet Support Learn More Button Clicked',
  LimitedWalletSupportToastShown = 'Limited Wallet Support Toast Shown',
  LiquidityGasEstimation = 'Liquidity Gas Estimation',
  LimitExpirySelected = 'Limit Expiry Selected',
  LimitPresetRateSelected = 'Limit Preset Rate Selected',
  LimitPriceReversed = 'Limit Price Reversed',
  LocalCurrencySelected = 'Local Currency Selected',
  MigrateLiquidityFailed = 'Migrate Liquidity Failed',
  MiniPortfolioToggled = 'Mini Portfolio Drawer Toggled',
  NavbarResultSelected = 'Navbar Result Selected',
  NotificationDismissed = 'Notification Dismissed',
  NotificationInteracted = 'Notification Interacted',
  NotificationReceived = 'Notification Received',
  NotificationShown = 'Notification Shown',
  NavbarSearchExited = 'Navbar Search Exited',
  NavbarSearchSelected = 'Navbar Search Selected',
  NoQuoteReceivedFromQuickrouteAPI = 'No quote received from quickroute API',
  NoQuoteReceivedFromRoutingAPI = 'No quote received from routing API',
  OnChainAddLiquidityFailed = 'On Chain Add Liquidity Failed',
  PortfolioMenuOpened = 'Portfolio Menu Opened',
  RiskChecked = 'Risk Checked',
  SendInitiated = 'Send Initiated',
  SendRecipientSelected = 'Send Recipient Selected',
  /**
   * @deprecated Misleading name: This event fires for ALL transaction types (swaps, approvals, wraps, sends, etc.),
   * not just swaps. Use the `transactionType` property to filter for actual swaps.
   * TODO: Rename to `TransactionConfirmedOnClient` or split into transaction-type-specific events
   * to improve analytics hygiene and align with mobile/extension which use separate events per type.
   */
  SwapConfirmedOnClient = 'Swap Confirmed on Client',
  SwapTabClicked = 'Swap Tab Clicked',
  TokenImported = 'Token Imported',
  TokenSelected = 'Token Selected',
  TokenSelectorOpened = 'Token Selector Opened',
  LxWalletAppDownloadOpened = 'Lx Wallet App Download Opened',
  LxWalletConnectModalOpened = 'Lx wallet modal opened',
  LxWalletMicrositeOpened = 'Lx Wallet Microsite Opened',
  LxSwapOrderCancelInitiated = 'LX Order Cancel Initiated',
  LxSwapOrderDetailsSheetOpened = 'LX Order Details Sheet Opened',
  LxSwapOrderPostError = 'LX Order Post Error',
  LxSwapOrderSubmitted = 'LX Order Submitted',
  LXSignatureDeadlineExpired = 'LX Signature Deadline Expired',
  LXSignatureRequested = 'LX Signature Requested',
  WalletCapabilitiesDetected = 'Wallet Capabilities Detected',
  WalletConnected = 'Wallet Connected',
  WalletProviderUsed = 'Wallet Provider Used',
  WalletSelected = 'Wallet Selected',
  WrapTokenTxnInvalidated = 'Wrap Token Transaction Invalidated',
  WrapTokenTxnSubmitted = 'Wrap Token Transaction Submitted',
  // alphabetize additional values.
}
